const jackPotPrize = 50;
const bonusesArray = [
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 5 },
  { cellChange: 0, prize: 10 },
  { cellChange: 0, prize: 10 },
  { cellChange: 0, prize: 10 },
  { cellChange: 0, prize: 10 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: -5 },
  { cellChange: 0, prize: jackPotPrize, isJackPot: true },
];
const configuration = {
  mapSize: 50,
  finishPosition: 51,
  bonusesArray: bonusesArray,
  initialCashValue: 50,
  minNumberOfSteps: 1,
  maxNumberOfSteps: 5,
};

const MOVE_TYPES = {
  MOVE_WITH_JACKPOT: "moveWithJackpot",
  MOVE_WITH_EMPTY_JACKPOT: "moveWithEmptyJackpot",
  MOVE_WITH_INCREASING_PRIZE: "moveWithIncreasingPrize",
  MOVE_WITH_DECREASING_PRIZE: "moveWithDecreasingPrize",
  MOVE_WITHOUT_BONUS: "moveWithoutBonus",
  MOVE_TO_FINISH: "moveToFinish",
};
