services:
  mongo:
    image: mongo:8.0.29
    container_name: bk-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - bk-app-mongo-data:/data/db
    restart: unless-stopped

volumes:
  bk-app-mongo-data:
