import type { WithId } from "mongodb";
import type { CurrentUser } from "../auth/domain/types";
import { LottoBingoEngine } from "./LottoBingoEngine";
import type { LottoBingoGameListItemView, LottoBingoGameView, LottoBingoPayoutView, LottoBingoRound, LottoBingoRoundWinnerView } from "./domain/types";
import type { LottoBingoGameDocument } from "./LottoBingoRepository";

export class LottoBingoReadModelFactory {
  constructor(private readonly engine: LottoBingoEngine) {}

  create(document: WithId<LottoBingoGameDocument>, actor: CurrentUser): LottoBingoGameView {
    const { _id, ...game } = document; const manage = actor.role === "admin" || actor.id === game.hostUserId; const phase = this.engine.getPhase(game); const activeRound = this.engine.getActiveRound(game); const candidates = this.engine.getCandidates(game); const drawnNumbers = this.engine.getDrawnNumbers(game); const canManageInProgress = manage && game.status === "in_progress";
    return { id: _id.toHexString(), createdAt: game.createdAt, updatedAt: game.updatedAt,
      meta: { projectId: game.projectId, configId: game.configId, configName: game.configName, status: game.status, phase, revision: game.revision, host: structuredClone(game.hostSnapshot), startedAt: game.startedAt, finishedAt: game.finishedAt, access: { mode: manage ? "manage" : "read_only", canAddPlayer: manage && game.status === "preparing", canRemovePlayer: manage && game.status === "preparing", canStart: manage && game.status === "preparing" && game.players.length > 0, canDraw: canManageInProgress && !!game.draw && game.draw.cursor < game.draw.plannedOrder.length, canUndoDraw: canManageInProgress && game.lastMutation === "barrel_drawn", canConfirmWinner: canManageInProgress && candidates.length > 0, canDisqualifyPlayer: canManageInProgress, canRestorePlayer: canManageInProgress, canFinalize: canManageInProgress && !!game.draw && game.draw.cursor === game.draw.plannedOrder.length, canDelete: manage } },
      configuration: { rules: structuredClone(game.rules), resources: structuredClone(game.resources) },
      state: { draw: { currentBarrel: drawnNumbers.at(-1) ?? null, drawnNumbers, drawnCount: drawnNumbers.length, plannedDrawCount: game.draw?.plannedOrder.length ?? 0, plannedRemainingCount: game.draw ? game.draw.plannedOrder.length - game.draw.cursor : 0, outOfGameCount: game.draw?.outOfGameNumbers.length ?? 90 - game.rules.barrelsToDraw }, round: { activeRound, candidates, hasUnconfirmedCandidates: candidates.length > 0, requiresDrawWithoutWinnerConfirmation: candidates.length > 0 }, players: game.players.map((player) => { const progress = this.engine.getProgress(game, player); const candidate = candidates.find((value) => value.playerId === player.id); return { id: player.id, nickname: player.nickname, ticket: structuredClone(player.ticket), status: player.status, progress: { ...progress, matchedCount: progress.matchedNumbers.length, remainingCount: progress.remainingNumbers.length }, eligibility: { isCurrentRoundCandidate: !!candidate, eligibleSinceDraw: candidate?.eligibleSinceDraw ?? null, excludedFromRoundRewards: player.award?.type === "round" || player.status === "disqualified", excludedFromFinalRewards: player.award?.type === "round" || player.status === "disqualified" }, award: structuredClone(player.award) }; }), winners: { round1: this.winners(game, 1), round2: this.winners(game, 2), round3: this.winners(game, 3) }, rewards: { roundPayouts: game.payouts.filter((payout) => payout.category.startsWith("round")).map((payout) => this.payout(game, payout)), finalPreview: game.status === "in_progress" && game.draw !== null && game.draw.cursor === game.draw.plannedOrder.length ? this.finalPreview(game) : null, finalPayouts: game.payouts.filter((payout) => !payout.category.startsWith("round")).map((payout) => this.payout(game, payout)) }, timeline: game.audit.map((event) => ({ id: event.id, type: event.type, createdAt: event.createdAt, actorName: event.actor.nickname, message: this.timelineMessage(event.type) })) }
    };
  }

  createListItem(document: WithId<LottoBingoGameDocument>): LottoBingoGameListItemView { const { _id, ...game } = document; return { id: _id.toHexString(), createdAt: game.createdAt, updatedAt: game.updatedAt, meta: { projectId: game.projectId, configId: game.configId, configName: game.configName, status: game.status, phase: this.engine.getPhase(game), host: structuredClone(game.hostSnapshot), startedAt: game.startedAt, finishedAt: game.finishedAt }, state: { playersCount: game.players.length, drawnBarrelsCount: this.engine.getDrawnNumbers(game).length, winners: { round1: game.winners.round1.map((winner) => winner.playerId), round2: game.winners.round2.map((winner) => winner.playerId), round3: game.winners.round3.map((winner) => winner.playerId) } } }; }
  private winners(game: LottoBingoGameDocument, round: LottoBingoRound): LottoBingoRoundWinnerView[] { return game.winners[`round${round}`].map((winner) => ({ ...winner, nickname: this.name(game, winner.playerId), rewards: structuredClone(game.payouts.find((payout) => payout.id === winner.payoutId)?.resolvedRewards ?? []) })); }
  private payout(game: LottoBingoGameDocument, payout: LottoBingoGameDocument["payouts"][number]): LottoBingoPayoutView { return { ...structuredClone(payout), nickname: this.name(game, payout.playerId) }; }
  private finalPreview(game: LottoBingoGameDocument) { const completed = game.players.filter((player) => player.status === "active" && this.engine.getProgress(game, player).completedCard); const consolation = game.players.filter((player) => player.status === "active" && !this.engine.getProgress(game, player).completedCard); return { completedCardPlayers: completed.map((player) => ({ playerId: player.id, nickname: player.nickname, projectedRewards: game.rules.rewards.completedCard.mode === "all" ? structuredClone(game.rules.rewards.completedCard.rewards) : [] })), consolationPlayers: consolation.map((player) => ({ playerId: player.id, nickname: player.nickname, projectedRewards: game.rules.rewards.consolation.mode === "all" ? structuredClone(game.rules.rewards.consolation.rewards) : [] })) }; }
  private name(game: LottoBingoGameDocument, playerId: string) { return game.players.find((player) => player.id === playerId)?.nickname ?? playerId; }
  private timelineMessage(type: string) { return ({ game_created: "Game created", player_added: "Player added", player_removed: "Player removed", game_started: "Game started", barrel_drawn: "Barrel drawn", barrel_undone: "Barrel draw undone", winner_confirmed: "Round winners confirmed", player_disqualified: "Player disqualified", player_restored: "Player restored", game_finished: "Game finished" } as Record<string, string>)[type] ?? type; }
}
