export const appHeaderTexts = {
  brandTitle: "Combats DJ",
  brandSubtitle: "Панель ведущего форумных игр",
  djNameLabel: "Ник ведущего",
  djNamePlaceholder: "Введите ник ведущего",
  projectLabel: "Проект",
  nav: {
    games: "Игры",
    activities: "Активности",
    analytics: "Аналитика",
    settings: "Настройки",
    journey: "Карта Мародёров",
    lotto: "Лото",
    battleship: "Морской бой",
    project: "Проект",
    configs: "Игры",
    quizConfigs: "Викторины",
    users: "Пользователи",
  },
};
