export const journeyTexts = {
  breadcrumbs: "Combats DJ / Карта Мародёров",
  pageTitle: "Карта Мародёров",
  pageDescription: "Рабочий экран ведущего: запуск партии, ввод ходов, карта, состояние игроков и готовый лог для форума.",
  actions: {
    importPlayersFromForum: "Игроки из топика",
    importMovesFromForum: "Считать из топика",
    applyForumMoves: "Заполнить ходы",
    rules: "Правила",
    newGame: "Новая игра",
    restore: "Восстановить",
    reset: "Сбросить",
    close: "Закрыть",
    apply: "Применить",
    cancel: "Отмена",
    addPlayer: "Добавить игрока",
    importPlayers: "Импорт игроков",
    importMoves: "Импорт ходов",
    applyMove: "Применить ход",
    getForumState: "Получить состояние",
    copy: "Скопировать",
    copied: "Скопировано",
  },
  statuses: {
    notStarted: "Игра не начата",
    active: "Игра активна",
    complete: "Игра завершена",
    rulesetPrefix: "Пресет:",
    djPrefix: "Ведущий:",
    roundPrefix: "Раунд",
    playersSuffix: "игрока",
  },
  alerts: {
    setDjName: "Укажите ник ведущего в верхнем меню, если нужен импорт игроков из форумного текста.",
    createOrRestoreGame: "Создайте или восстановите партию, чтобы увидеть состояние игры.",
    logEmpty: "Лог пока пуст. После первого хода здесь появятся все события партии.",
    forumStateUnavailable: "Состояние игры пока не получено.",
    forumStateCopyFailed: "Не удалось скопировать текст.",
    allPlayersFinished: "Все игроки уже на финише.",
    resultsCompletePrefix: "Игра завершена. На финише",
    resultsCompleteSuffix: "игрок(ов).",
  },
  rulesDialogTitle: "Правила Journey",
  rulesSummaryTitle: "Текущее состояние правил игры",
  rulesChips: {
    startPrefix: "Старт",
    mapPrefix: "Карта",
    mapSuffix: "клеток",
    movePrefix: "Ход",
    jackpotPrefix: "Сокровище",
    prizeLimitPrefix: "Лимит обычной награды",
    noPrizeLimit: "Без лимита обычной награды",
  },
  cards: {
    playersTitle: "Игроки",
    playersSubtitle: "Можно вручную, можно вставкой из форума",
    movesTitle: "Ходы",
    movesSubtitle: "Ходы активных игроков и ручные пропуски",
    mapTitle: "Карта",
    mapSubtitlePrefix: "Полная карта ведущего:",
    mapSubtitleSuffix: "клеток и позиции игроков",
    stateTitle: "Состояние игры",
    stateSubtitle: "Актуальные позиции и общий приз игроков",
    logTitle: "Лог игры",
    logSubtitle: "Пошаговый лог партии с комментариями по раундам",
    resultsTitle: "Результаты",
    resultsSubtitle: "Финальная таблица и размен чеков",
  },
  dialogTitles: {
    forumState: "Текущее состояние",
    forumMovesPreview: "Ходы из топика",
    playersImport: "Импорт игроков",
    movesImport: "Импорт ходов",
  },
  fields: {
    forumTopic: "Номер топика",
    forumText: "Текст с форума",
    move: "Ход",
    skip: "Пропуск",
    playerPrefix: "Игрок",
  },
  placeholders: {
    forumTopic: "Напр. 123456",
  },
  forumPreview: {
    summary: (topicId: number, roundIndex: number) => `Топик №${topicId}. Найдены ходы для раунда ${roundIndex}.`,
    detectedMoves: "Найденные ходы",
    player: "Игрок",
    move: "Ход",
    message: "Сообщение",
    noMoves: "Подходящих ходов в новых сообщениях не найдено.",
    ignoredTitle: "Пропущенные сообщения",
    ignoredReasons: {
      player_not_active: "автор не является активным игроком",
      dice_not_found: "не найдено число хода",
      dice_out_of_range: "число хода вне допустимого диапазона",
    },
  },
  helperText: {
    playersImport: "Поддерживается текущий legacy-формат разбора.",
    movesImport: "Legacy-парсер строк ник/число сохранён.",
  },
  validation: {
    invalidForumTopic: "Номер топика должен быть положительным целым числом",
    fillNickname: "Заполните ник",
    duplicateNickname: "Ник дублируется",
  },
  mapLegend: {
    empty: "· Пусто",
    bonus: "S/M/L Бонус",
    trap: "S/M/L Ловушка",
    treasure: "🏆 Сокровище",
  },
  hover: {
    jackpotFoundPrefix: "Сокровище уже найдено игроком",
    jackpotNotFound: "Сокровище ещё не найдено.",
    bonusPrefix: "На клетке бонус",
    trapPrefix: "На клетке ловушка",
    cellEmpty: "Пустая клетка без бонусов и ловушек.",
    playersOnCell: "Игроки на клетке",
    noPlayersOnCell: "Сейчас никого нет.",
    cellPrefix: "Клетка",
  },
  results: {
    receiptsTitle: "Размен чеков",
  },
  table: {
    player: "Игрок",
    cell: "Клетка",
    base: "База",
    withBonuses: "С бонусами",
    achievements: "Достижения",
    removed: "Удалён",
    finish: "Финиш",
    treasure: "Сокровище",
  },
  progress: {
    title: "Прогресс достижений",
    historyTitle: "История игрока",
    obtained: "Получено",
    missing: "Не получено",
    nothingYet: "Пока ничего.",
    allCollected: "Всё собрано.",
    inProgress: "В процессе",
    currentSeries: "Текущая серия",
    maximum: "Максимум",
    of: "из",
    historyEmpty: "История пока пустая.",
  },
  timeline: {
    skipSuffix: "пропуск",
    treasure: "сокровище",
    bonusPrefix: "бонус",
    trapPrefix: "ловушка",
    empty: "пусто",
    change: "изменение",
    total: "итог",
    turnPrefix: "Ход",
  },
  tooltips: {
    removePlayer: "Удалить игрока из текущей партии",
  },
};
