export const quizConfigsTexts = {
  page: {
    breadcrumb: "Викторины",
    title: "Конфиги викторин",
    description: "Выберите готовый набор правил, наград и сообщений для новой викторины.",
    projectChip: (projectName: string) => `Проект: ${projectName}`,
    configsChip: (count: number) => `Конфигов: ${count}`,
    refresh: "Обновить",
  },
  section: {
    title: "Доступные конфиги",
    description: "Готовый конфиг можно выбрать для подготовки викторины.",
    searchPlaceholder: "Найти конфиг",
  },
  card: {
    untitled: "Без названия",
    noDescription: "Описание не добавлено.",
    ready: "Готов",
    draft: "Черновик",
    system: "Системный",
    questionCount: "Вопросы",
    questionsValue: (count: number) => `${count} вопросов`,
    regularRewards: "Награды за ответ",
    regularRewardAllAccepted: "Всем правильно ответившим",
    regularRewardByPosition: (count: number) => `По местам: ${count}`,
    bonusRewards: "Бонусные награды",
    bonusRulesValue: (count: number) => count ? `Правил: ${count}` : "Нет",
    messages: "Сообщения",
    messagesConfigured: "Настроены",
    notConfigured: "Не настроено",
    appliesToNewQuizzes: "Применяется к новым викторинам",
    open: "Открыть",
  },
  editor: {
    pageDescription: "Правила, награды и шаблоны сообщений для новых викторин.",
    configChip: "Викторины",
    changesChip: (count: number) => count ? `Изменений: ${count}` : "Изменений нет",
    save: "Сохранить",
    reset: "Сбросить",
    sections: {
      heading: "Разделы",
      description: "Настройки конфига",
      changedHint: "Изменённые разделы отмечены индикатором. Сохраняется весь конфиг целиком.",
      details: {
        description: {
          label: "Описание",
          description: "Название и параметры",
          title: "Описание викторины",
          details: "Название, описание и количество вопросов для этого конфига.",
        },
        rewards: {
          label: "Награды",
          description: "За вопросы и места",
          title: "Награды игрокам",
          details: "Правила наград за правильные ответы, отдельные вопросы и места.",
        },
        messages: {
          label: "Сообщения",
          description: "Шаблоны для чата",
          title: "Шаблоны сообщений",
          details: "Тексты вопросов и правильных ответов для публикации в чате.",
        },
      },
    },
    description: {
      title: "Сведения о конфиге",
      details: "Отображаются в списке конфигов и используются при создании викторины.",
      name: "Название",
      configDescription: "Описание",
      questionCount: "Количество вопросов",
      summaryTitle: "Сводка текущих правил",
      summaryDescription: "Ключевые параметры выбранного конфига.",
      status: "Статус",
    },
    rewards: {
      title: "Награды игрокам",
      description: "Настройте награды за правильные ответы, отдельные вопросы и места.",
    },
    messages: {
      title: "Сообщения",
      description: "Настройте шаблоны, которые ведущий будет использовать для вопросов и правильных ответов.",
      availableVariables: "Доступны переменные: questionNumber, questionTitle, questionText, attachment, correctAnswer, quizName, hostName, emojiStart, emojiEnd.",
      question: "Вопрос",
      answer: "Правильный ответ",
    },
    alerts: {
      projectRequired: "Выберите проект, чтобы открыть конфиг викторины.",
      loadFailed: "Не удалось загрузить или сохранить конфиг викторины.",
      notFound: "Конфиг викторины не найден в выбранном проекте.",
      viewOnly: "Этот конфиг доступен только для просмотра. Создайте свою копию системного конфига, чтобы изменить правила.",
    },
  },
  empty: {
    noConfigsTitle: "Конфигов пока нет",
    noConfigsDescription: "Создание новых конфигов будет добавлено отдельной страницей.",
    searchTitle: "Ничего не найдено",
    searchDescription: "Измените поисковый запрос.",
  },
  alerts: {
    projectRequired: "Выберите проект, чтобы просматривать его конфиги викторин.",
    loadFailed: "Не удалось загрузить конфиги викторин.",
  },
} as const;
