export const quizConfigsTexts = {
  page: {
    breadcrumb: "Викторины",
    title: "Конфиги викторин",
    description: "Выберите готовый набор правил, наград и сообщений для новой викторины.",
    projectChip: (projectName: string) => `Проект: ${projectName}`,
    configsChip: (count: number) => `Конфигов: ${count}`,
    refresh: "Обновить",
  },
  section: {
    title: "Доступные конфиги",
    description: "Готовый конфиг можно выбрать для подготовки викторины.",
    searchPlaceholder: "Найти конфиг",
  },
  card: {
    untitled: "Без названия",
    noDescription: "Описание не добавлено.",
    ready: "Готов",
    draft: "Черновик",
    system: "Системный",
    questionCount: "Вопросы",
    questionsValue: (count: number) => `${count} вопросов`,
    regularRewards: "Награды за ответ",
    regularRewardAllAccepted: "Всем правильно ответившим",
    regularRewardByPosition: (count: number) => `По местам: ${count}`,
    bonusRewards: "Бонусные награды",
    bonusRulesValue: (count: number) => count ? `Правил: ${count}` : "Нет",
    messages: "Сообщения",
    messagesConfigured: "Настроены",
    notConfigured: "Не настроено",
    appliesToNewQuizzes: "Применяется к новым викторинам",
    select: "Выбрать",
  },
  empty: {
    noConfigsTitle: "Конфигов пока нет",
    noConfigsDescription: "Создание и редактирование конфигов будет добавлено отдельной страницей.",
    searchTitle: "Ничего не найдено",
    searchDescription: "Измените поисковый запрос.",
  },
  alerts: {
    projectRequired: "Выберите проект, чтобы просматривать его конфиги викторин.",
    loadFailed: "Не удалось загрузить конфиги викторин.",
  },
} as const;
