export const quizConfigsTexts = {
  page: {
    breadcrumb: "Викторины",
    title: "Конфиги викторин",
    description: "Выберите готовый набор правил, наград и сообщений для новой викторины.",
    projectChip: (projectName: string) => `Проект: ${projectName}`,
    configsChip: (count: number) => `Конфигов: ${count}`,
    systemConfigsChip: (count: number) => `Системных: ${count}`,
    draftConfigsChip: (count: number) => `Черновиков: ${count}`,
    create: "Создать",
    refresh: "Обновить",
  },
  section: {
    title: "Доступные конфиги",
    description: "Системные используются как базовые. Личные можно изменять и удалять.",
    searchPlaceholder: "Найти конфиг",
    searchHint: "Поиск появится, когда конфигов станет 4 или больше.",
  },
  card: {
    untitled: "Без названия",
    noDescription: "Описание не добавлено.",
    ready: "Готов",
    draft: "Черновик",
    system: "Системный",
    questionCount: "Вопросы",
    questionsValue: (count: number) => `${count} вопросов`,
    regularRewards: "Награды за ответ",
    baseReward: "Базовая награда",
    baseRewards: "Базовые награды",
    rewardPerCorrectAnswer: "За каждый правильный ответ",
    positionRewards: (count: number) => `По местам: ${count}`,
    incompleteRules: "Правила заполнены частично",
    rewardNotConfigured: "—",
    regularRewardAllAccepted: "Всем правильно ответившим",
    regularRewardByPosition: (count: number) => `По местам: ${count}`,
    bonusRewards: "Бонусные награды",
    bonusRulesValue: (count: number) => count ? `Правил: ${count}` : "Нет правил",
    messages: "Сообщения",
    messagesConfigured: "Вопрос и ответ настроены",
    notConfigured: "Не настроено",
    appliesToNewQuizzes: "Применяется к новым викторинам",
    open: "Открыть",
    edit: "Изменить",
    view: "Открыть",
    delete: "Удалить",
    clone: "Сделать дубликат",
    cloneUnavailable: "Дублирование скоро появится.",
    menuAriaLabel: "Действия с конфигом",
    systemConfig: "Системный конфиг",
    personalConfig: "Личный конфиг",
    unknownDate: "Дата не указана",
    updatedAt: (date: string) => `Изменён ${date}`,
  },
  editor: {
    pageDescription: "Правила, награды и шаблоны сообщений для новых викторин.",
    configChip: "Викторины",
    changesChip: (count: number) => count ? `Изменений: ${count}` : "Изменений нет",
    save: "Сохранить",
    reset: "Сбросить",
    sections: {
      heading: "Разделы",
      description: "Настройки конфига",
      changedHint: "Изменённые разделы отмечены индикатором. Сохраняется весь конфиг целиком.",
      details: {
        description: {
          label: "Описание",
          description: "Название и параметры",
          title: "Описание викторины",
          details: "Название, описание и количество вопросов для этого конфига.",
        },
        rewards: {
          label: "Награды",
          description: "За вопросы и места",
          title: "Награды игрокам",
          details: "Правила наград за правильные ответы, отдельные вопросы и места.",
        },
        messages: {
          label: "Сообщения",
          description: "Шаблоны для чата",
          title: "Шаблоны сообщений",
          details: "Тексты вопросов и правильных ответов для публикации в чате.",
        },
      },
    },
    description: {
      title: "Сведения о конфиге",
      details: "Отображаются в списке конфигов и используются при создании викторины.",
      name: "Название",
      configDescription: "Описание",
      questionCount: "Количество вопросов",
      summaryTitle: "Сводка текущих правил",
      summaryDescription: "Ключевые параметры выбранного конфига.",
      status: "Статус",
    },
    rewards: {
      title: "Награды игрокам",
      description: "Настройте награды за правильные ответы, отдельные вопросы и места.",
    },
    messages: {
      title: "Сообщения",
      description: "Настройте шаблоны, которые ведущий будет использовать для вопросов и правильных ответов.",
      availableVariables: "Доступны переменные: questionNumber, questionTitle, questionText, attachment, correctAnswer, quizName, hostName, emojiStart, emojiEnd.",
      question: "Вопрос",
      answer: "Правильный ответ",
    },
    alerts: {
      projectRequired: "Выберите проект, чтобы открыть конфиг викторины.",
      loadFailed: "Не удалось загрузить или сохранить конфиг викторины.",
      notFound: "Конфиг викторины не найден в выбранном проекте.",
      viewOnly: "Этот конфиг доступен только для просмотра. Создайте свою копию системного конфига, чтобы изменить правила.",
    },
  },
  create: {
    title: "Новый конфиг викторины",
    description: "Настройте правила, награды и шаблоны сообщений для новой викторины.",
    create: "Создать конфиг",
    requiredFields: "Заполните обязательные поля, чтобы создать конфиг:",
    required: {
      name: "Название конфига",
      questionCount: "Количество вопросов",
      regularReward: "Правило обычной награды",
      regularRewardPool: "Хотя бы одна награда в правиле обычной награды",
      questionTemplate: "Шаблон сообщения вопроса",
      answerTemplate: "Шаблон сообщения правильного ответа",
    },
    alerts: {
      projectRequired: "Выберите проект, чтобы создать конфиг викторины.",
      createFailed: "Не удалось создать конфиг викторины.",
    },
  },
  empty: {
    noConfigsTitle: "Конфигов пока нет",
    noConfigsDescription: "Создание новых конфигов будет добавлено отдельной страницей.",
    searchTitle: "Ничего не найдено",
    searchDescription: "Измените поисковый запрос.",
  },
  alerts: {
    projectRequired: "Выберите проект, чтобы просматривать его конфиги викторин.",
    loadFailed: "Не удалось загрузить конфиги викторин.",
    deleteFailed: "Не удалось удалить конфиг викторины.",
  },
  deleteDialog: {
    title: "Удалить конфиг?",
    description: (configName: string) => `Конфиг «${configName}» будет удалён без возможности восстановления.`,
    confirm: "Удалить",
    cancel: "Отмена",
  },
} as const;
