import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import PlayArrowRoundedIcon from "@mui/icons-material/PlayArrowRounded";
import SaveRoundedIcon from "@mui/icons-material/SaveRounded";
import { Alert, Card, CardContent, Chip, Stack, Typography } from "@mui/material";
import AppPillButton from "../../../../components/ui/AppPillButton";
import AppTextInput from "../../../../components/ui/AppTextInput";
import { formatResourceAmounts } from "../../../rewards/resourceAmounts";
import { getQuizAuthorLabel } from "../quizAuthor.helpers";
import QuizTemplatesEditor from "./QuizTemplatesEditor";
import type { Quiz } from "../types";

interface Props { quiz: Quiz; disabled: boolean; isDirty: boolean; onChange: (quiz: Quiz) => void; onSave: () => void; onReset: () => void; onRun: () => void; onDelete: () => void; }

export default function QuizEditor({ quiz, disabled, isDirty, onChange, onSave, onReset, onRun, onDelete }: Props) {
  const update = (next: Partial<Quiz>) => onChange({ ...quiz, ...next });
  const updateQuestion = (index: number, field: "title" | "text" | "correctAnswer" | "attachmentUrl" | "notes", value: string) => update({ questions: quiz.questions.map((question, questionIndex) => questionIndex === index ? { ...question, [field]: value || null } : question) });
  const rewards = quiz.configRulesSnapshot ? formatResourceAmounts(quiz.configRulesSnapshot.defaultRegularRule.mode === "all_accepted" ? quiz.configRulesSnapshot.defaultRegularRule.rewardPool.rewards : [], quiz.resources) : "";
  return <Stack spacing={2.25}>
    <Card><CardContent><Stack spacing={1.5}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" spacing={1} alignItems={{ sm: "center" }}><Typography variant="h5">{quiz.name || "Новая викторина"}</Typography><Stack direction="row" spacing={1}><Chip label={quiz.status} color={quiz.status === "ready" ? "success" : "warning"} />{isDirty ? <Chip label="Не сохранено" color="info" /> : null}</Stack></Stack><Typography variant="body2" color="text.secondary">Автор: {getQuizAuthorLabel(quiz.createdByNickname)} · Config: {quiz.configRulesSnapshot.configName}</Typography><AppTextInput label="Название" value={quiz.name} disabled={disabled} onChange={(event) => update({ name: event.target.value })} /><AppTextInput multiline minRows={2} label="Описание" value={quiz.description} disabled={disabled} onChange={(event) => update({ description: event.target.value })} />{quiz.validationIssues.length ? <Alert severity="warning"><Stack component="ul" sx={{ m: 0, pl: 2 }}>{quiz.validationIssues.map((issue, index) => <li key={`${issue.path}-${index}`}>{issue.message}</li>)}</Stack></Alert> : <Alert severity="success">Викторина готова к проведению.</Alert>}<Stack direction={{ xs: "column", sm: "row" }} spacing={1}><AppPillButton variant="contained" startIcon={<SaveRoundedIcon />} disabled={disabled || !isDirty} onClick={onSave}>Сохранить</AppPillButton>{isDirty ? <AppPillButton variant="outlined" disabled={disabled} onClick={onReset}>Сбросить изменения</AppPillButton> : null}<AppPillButton variant="outlined" startIcon={<PlayArrowRoundedIcon />} disabled={disabled || isDirty || quiz.status !== "ready"} onClick={onRun}>Провести</AppPillButton><AppPillButton variant="outlined" color="error" startIcon={<DeleteOutlineRoundedIcon />} disabled={disabled} onClick={onDelete}>Удалить</AppPillButton></Stack></Stack></CardContent></Card>
    <Card><CardContent><Stack spacing={1}><Typography variant="h5">Правила наград</Typography><Typography color="text.secondary">Источник: {quiz.configRulesSnapshot?.configName ?? quiz.configId}</Typography><Typography variant="body2">{quiz.configRulesSnapshot?.defaultRegularRule.mode === "by_position" ? "Награды распределяются по месту; правила доступны в исходном Config." : `Каждый принятый получает: ${rewards || "награды не заданы"}`}</Typography></Stack></CardContent></Card>
    <Card><CardContent><Stack spacing={2}><Typography variant="h5">Вопросы</Typography>{quiz.questions.map((question, index) => <Card variant="outlined" key={question.id}><CardContent><Stack spacing={1.25}><Typography fontWeight={700}>Вопрос {question.questionIndex}</Typography><AppTextInput label="Заголовок" value={question.title ?? ""} disabled={disabled} onChange={(event) => updateQuestion(index, "title", event.target.value)} /><AppTextInput multiline minRows={3} label="Текст вопроса" value={question.text} disabled={disabled} onChange={(event) => updateQuestion(index, "text", event.target.value)} /><AppTextInput label="Правильный ответ" value={question.correctAnswer ?? ""} disabled={disabled} onChange={(event) => updateQuestion(index, "correctAnswer", event.target.value)} /><AppTextInput label="URL вложения" value={question.attachmentUrl ?? ""} disabled={disabled} onChange={(event) => updateQuestion(index, "attachmentUrl", event.target.value)} /><AppTextInput multiline minRows={2} label="Заметка ведущего" value={question.notes ?? ""} disabled={disabled} onChange={(event) => updateQuestion(index, "notes", event.target.value)} /></Stack></CardContent></Card>)}</Stack></CardContent></Card>
    <Card><CardContent><Stack spacing={2}><Typography variant="h5">Шаблоны сообщений</Typography><Typography variant="subtitle1">Вопрос</Typography><QuizTemplatesEditor label="Вопрос" messageKind="question" templates={quiz.effectiveMessageTemplates} questionCount={quiz.questions.length} disabled={disabled} onChange={(effectiveMessageTemplates) => effectiveMessageTemplates && update({ effectiveMessageTemplates })} /><Typography variant="subtitle1">Правильный ответ</Typography><QuizTemplatesEditor label="Ответ" messageKind="answer" templates={quiz.effectiveAnswerMessageTemplates} questionCount={quiz.questions.length} disabled={disabled} onChange={(effectiveAnswerMessageTemplates) => effectiveAnswerMessageTemplates && update({ effectiveAnswerMessageTemplates })} /></Stack></CardContent></Card>
  </Stack>;
}
