import AddRoundedIcon from "@mui/icons-material/AddRounded";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import { Card, CardContent, IconButton, MenuItem, Stack, Typography } from "@mui/material";
import RewardPoolEditor, { createRewardPool } from "../../../configs/components/RewardPoolEditor";
import AppPillButton from "../../../../components/ui/AppPillButton";
import AppTextInput from "../../../../components/ui/AppTextInput";
import type { ProjectResource } from "../../../projects/types";
import type { QuizBonusRule, QuizRegularRewardOverride, QuizRegularRule, QuizRewardPool } from "../types";

interface Props {
  questionCount: number | null;
  resources: ProjectResource[];
  defaultRule: QuizRegularRule | null;
  overrides: QuizRegularRewardOverride[];
  bonuses: QuizBonusRule[];
  disabled: boolean;
  onChange: (next: { defaultRule: QuizRegularRule | null; overrides: QuizRegularRewardOverride[]; bonuses: QuizBonusRule[] }) => void;
}

const emptyPool = (resources: ProjectResource[]): QuizRewardPool => createRewardPool("all", resources) as QuizRewardPool;
const defaultRule = (resources: ProjectResource[]): QuizRegularRule => ({ mode: "all_accepted", rewardPool: emptyPool(resources) });

function RuleEditor({ value, resources, disabled, onChange }: { value: QuizRegularRule; resources: ProjectResource[]; disabled: boolean; onChange: (value: QuizRegularRule) => void }) {
  if (value.mode === "all_accepted") return <Stack spacing={1}><Typography variant="body2" color="text.secondary">Каждый уникальный принятый ответ получает:</Typography><RewardPoolEditor pool={value.rewardPool} resources={resources} disabled={disabled} showModeSelector={false} onChange={(rewardPool) => onChange({ mode: "all_accepted", rewardPool: rewardPool as QuizRewardPool })} /></Stack>;
  return <Stack spacing={1.5}>{value.positionRewards.map((entry, index) => <Card variant="outlined" key={index}><CardContent><Stack spacing={1}><Stack direction="row" spacing={1} alignItems="center"><AppTextInput type="number" size="small" label="Место" value={entry.position} disabled={disabled} inputProps={{ min: 1 }} onChange={(event) => onChange({ ...value, positionRewards: value.positionRewards.map((item, itemIndex) => itemIndex === index ? { ...item, position: Number(event.target.value) } : item) })} /><IconButton aria-label="Удалить награду за место" color="error" disabled={disabled} onClick={() => onChange({ ...value, positionRewards: value.positionRewards.filter((_item, itemIndex) => itemIndex !== index) })}><DeleteOutlineRoundedIcon /></IconButton></Stack><RewardPoolEditor pool={entry.rewardPool} resources={resources} disabled={disabled} showModeSelector={false} onChange={(rewardPool) => onChange({ ...value, positionRewards: value.positionRewards.map((item, itemIndex) => itemIndex === index ? { ...item, rewardPool: rewardPool as QuizRewardPool } : item) })} /></Stack></CardContent></Card>)}<AppPillButton size="small" variant="outlined" startIcon={<AddRoundedIcon />} disabled={disabled} onClick={() => onChange({ ...value, positionRewards: [...value.positionRewards, { position: value.positionRewards.length + 1, rewardPool: emptyPool(resources) }] })} sx={{ alignSelf: "flex-start" }}>Добавить место</AppPillButton></Stack>;
}

export default function QuizRewardsEditor({ questionCount, resources, defaultRule: currentDefaultRule, overrides, bonuses, disabled, onChange }: Props) {
  const update = (next: Partial<{ defaultRule: QuizRegularRule | null; overrides: QuizRegularRewardOverride[]; bonuses: QuizBonusRule[] }>) => onChange({ defaultRule: currentDefaultRule, overrides, bonuses, ...next });
  const availableIndex = (used: number[]) => Array.from({ length: questionCount ?? 0 }, (_value, offset) => offset + 1).find((index) => !used.includes(index)) ?? 1;
  return <Stack spacing={2.5}>
    <Stack spacing={1}><Typography variant="subtitle1">Обычная награда</Typography>{currentDefaultRule ? <><AppTextInput select size="small" label="Способ распределения" value={currentDefaultRule.mode} disabled={disabled} onChange={(event) => update({ defaultRule: event.target.value === "all_accepted" ? defaultRule(resources) : { mode: "by_position", positionRewards: [{ position: 1, rewardPool: emptyPool(resources) }] } })}><MenuItem value="all_accepted">Всем принятым</MenuItem><MenuItem value="by_position">По месту</MenuItem></AppTextInput><RuleEditor value={currentDefaultRule} resources={resources} disabled={disabled} onChange={(defaultRule) => update({ defaultRule })} /></> : <AppPillButton disabled={disabled} onClick={() => update({ defaultRule: defaultRule(resources) })}>Добавить правило</AppPillButton>}</Stack>
    <Stack spacing={1}><Typography variant="subtitle1">Переопределения по вопросам</Typography>{overrides.map((override, index) => <Card variant="outlined" key={index}><CardContent><Stack spacing={1.25}><Stack direction="row" spacing={1} alignItems="center"><AppTextInput type="number" size="small" label="Номер вопроса" value={override.questionIndex} disabled={disabled} inputProps={{ min: 1, max: questionCount ?? undefined }} onChange={(event) => update({ overrides: overrides.map((item, itemIndex) => itemIndex === index ? { ...item, questionIndex: Number(event.target.value) } : item) })} /><IconButton aria-label="Удалить переопределение награды" color="error" disabled={disabled} onClick={() => update({ overrides: overrides.filter((_item, itemIndex) => itemIndex !== index) })}><DeleteOutlineRoundedIcon /></IconButton></Stack><RuleEditor value={override.rule} resources={resources} disabled={disabled} onChange={(rule) => update({ overrides: overrides.map((item, itemIndex) => itemIndex === index ? { ...item, rule } : item) })} /></Stack></CardContent></Card>)}<AppPillButton size="small" variant="outlined" startIcon={<AddRoundedIcon />} disabled={disabled || !questionCount || overrides.length >= questionCount} onClick={() => update({ overrides: [...overrides, { questionIndex: availableIndex(overrides.map((item) => item.questionIndex)), rule: defaultRule(resources) }] })} sx={{ alignSelf: "flex-start" }}>Добавить переопределение</AppPillButton></Stack>
    <Stack spacing={1}><Typography variant="subtitle1">Бонусы за место</Typography>{bonuses.map((bonus, index) => <Card variant="outlined" key={bonus.id}><CardContent><Stack spacing={1.25}><Stack direction={{ xs: "column", sm: "row" }} spacing={1} alignItems={{ sm: "center" }}><AppTextInput type="number" size="small" label="Вопрос" value={bonus.questionIndex} disabled={disabled} inputProps={{ min: 1, max: questionCount ?? undefined }} onChange={(event) => update({ bonuses: bonuses.map((item, itemIndex) => itemIndex === index ? { ...item, questionIndex: Number(event.target.value) } : item) })} /><AppTextInput type="number" size="small" label="Место" value={bonus.position} disabled={disabled} inputProps={{ min: 1 }} onChange={(event) => update({ bonuses: bonuses.map((item, itemIndex) => itemIndex === index ? { ...item, position: Number(event.target.value) } : item) })} /><IconButton aria-label="Удалить бонус" color="error" disabled={disabled} onClick={() => update({ bonuses: bonuses.filter((_item, itemIndex) => itemIndex !== index) })}><DeleteOutlineRoundedIcon /></IconButton></Stack><RewardPoolEditor pool={bonus.rewardPool} resources={resources} disabled={disabled} showModeSelector={false} onChange={(rewardPool) => update({ bonuses: bonuses.map((item, itemIndex) => itemIndex === index ? { ...item, rewardPool: rewardPool as QuizRewardPool } : item) })} /></Stack></CardContent></Card>)}<AppPillButton size="small" variant="outlined" startIcon={<AddRoundedIcon />} disabled={disabled || !questionCount} onClick={() => update({ bonuses: [...bonuses, { id: crypto.randomUUID(), questionIndex: 1, position: 1, rewardPool: emptyPool(resources) }] })} sx={{ alignSelf: "flex-start" }}>Добавить бонус</AppPillButton></Stack>
  </Stack>;
}
