const configurationPageOptions = {
  loto: {
    inputs: {
      cardNumbersAmount: {
        divClasslist: "col-md-2 me-3",
        name: "Loto card numbers amount",
        type: "number",
        classlist: "form-control",
        placeholder: `Enter loto card numbers amount`,
        id: "loto-cardNumbersAmount",
        errorMessageSelector: "#error-loto-cardNumbersAmount",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Loto card numbers amount"),
        attributes: `name="loto-cardNumbersAmount" disabled`,
        value: "",
      },
      min: {
        divClasslist: "col-md-2 me-3",
        name: "Min value",
        type: "number",
        classlist: "form-control",
        placeholder: `Enter minimum value`,
        id: "loto-inputMin",
        errorMessageSelector: "#error-loto-inputMin",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Loto minimum"),
        attributes: `name="loto-min" disabled`,
        value: "",
      },
      max: {
        divClasslist: "col-md-2 me-3",
        name: "Max value",
        type: "number",
        classlist: "form-control",
        placeholder: `Enter maximum value`,
        id: "loto-inputMax",
        errorMessageSelector: "#error-loto-inputMax",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Loto maximum"),
        attributes: `name="loto-max" disabled`,
        value: "",
      },
    },
  },
  battleships: {
    inputs: {
      "single-deck": {
        divClasslist: "col-md-2 me-2",
        name: "Single-deck ships",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of single-deck ships`,
        id: "battleships-single-deck",
        errorMessageSelector: "#error-battleships-single-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Number of single-deck ships"),
        attributes: `name="battleships-single-deck" disabled`,
        value: "",
      },
      "double-deck": {
        divClasslist: "col-md-2 me-2",
        name: "Double-deck ships",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of double-deck ships`,
        id: "battleships-double-deck",
        errorMessageSelector: "#error-battleships-double-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Number of double-deck ships"),
        attributes: `name="battleships-double-deck" disabled`,
        value: "",
      },
      "three-deck": {
        divClasslist: "col-md-2 me-2",
        name: "Three-deck ships",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of three-deck ships`,
        id: "battleships-three-deck",
        errorMessageSelector: "#error-battleships-three-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Number of three-deck ships"),
        attributes: `name="battleships-three-deck" disabled`,
        value: "",
      },
      "four-deck": {
        divClasslist: "col-md-2 me-2",
        name: "Four-deck ships",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of four-deck ships`,
        id: "battleships-four-deck",
        errorMessageSelector: "#error-battleships-four-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Number of four-deck ships"),
        attributes: `name="battleships-four-deck" disabled`,
        value: "",
      },
      "single-deck-kill-prize": {
        divClasslist: "col-md-2 me-2",
        name: "Prize for single-deck ship kill",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of single-deck ships`,
        id: "battleships-single-deck-kill-prize",
        errorMessageSelector: "#error-battleships-single-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Prize for single-deck ship kill"),
        attributes: `name="battleships-single-deck-kill-prize" disabled`,
        value: "",
      },
      "double-deck-kill-prize": {
        divClasslist: "col-md-2 me-2",
        name: "Prize for double-deck ship kill",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of double-deck ships`,
        id: "battleships-double-deck-kill-prize",
        errorMessageSelector: "#error-battleships-double-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Prize for double-deck ship kill"),
        attributes: `name="battleships-double-deck-kill-prize" disabled`,
        value: "",
      },
      "three-deck-kill-prize": {
        divClasslist: "col-md-2 me-2",
        name: "Prize for three-deck ship kill",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of three-deck ships`,
        id: "battleships-three-deck-kill-prize",
        errorMessageSelector: "#error-battleships-three-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Prize for three-deck ship kill"),
        attributes: `name="battleships-three-deck-kill-prize" disabled`,
        value: "",
      },
      "four-deck-kill-prize": {
        divClasslist: "col-md-2 me-2",
        name: "Prize for four-deck ship kill",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of four-deck ships`,
        id: "battleships-four-deck-kill-prize",
        errorMessageSelector: "#error-battleships-four-deck",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Prize for four-deck ship kill"),
        attributes: `name="battleships-four-deck-kill-prize" disabled`,
        value: "",
      },
      attempts: {
        divClasslist: "col-md-2 me-2",
        name: "Attempts",
        type: "number",
        classlist: "form-control",
        placeholder: `Number of attempts`,
        id: "battleships-attempts",
        errorMessageSelector: "#error-battleships-attempts",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Number of attempts"),
        attributes: `name="battleships-attempts" disabled`,
        value: "",
      },
      currency: {
        divClasslist: "col-md-3 me-2",
        name: "Currency name",
        type: "text",
        classlist: "form-control",
        placeholder: `Enter currency name`,
        id: "loto-currency",
        errorMessageSelector: "#error-loto-currency",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Currency name"),
        attributes: `name="loto-currency" disabled`,
        value: "",
      },
      hitPrize: {
        divClasslist: "col-md-2 me-2",
        name: "Hit prize",
        type: "number",
        classlist: "form-control",
        placeholder: `Hit prize`,
        id: "battleships-hit-prize",
        errorMessageSelector: "#error-battleships-hit-prize",
        errorMessage: validationErrorMessages["NOT_EMPTY"]("Hit prize"),
        attributes: `name="battleships-hit-prize" disabled`,
        value: "",
      },
    },
  },
  labyrinth: {
    inputs: {},
  },
};

const initialConfig = {
  battleShips: {
    boardSize: 6,
    ships: [
      { size: 3, amount: 1 },
      { size: 2, amount: 2 },
      { size: 1, amount: 4 },
    ],
    maxShots: 17,
    currency: "фишки",
    prizes: {
      shoot: 2,
      destroyBonus: {
        3: 2,
        2: 1,
        1: 1,
      },
    },
  },
  labyrinth: {
    mapSize: 50,
    finishPosition: 51,
    bonusesArray: [
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 2 },
      { cellChange: 0, prize: 3 },
      { cellChange: 0, prize: 3 },
      { cellChange: 0, prize: 3 },
      { cellChange: 0, prize: 3 },
      { cellChange: 0, prize: 3 },
      { cellChange: 0, prize: 5 },
      { cellChange: 0, prize: 5 },
      { cellChange: 0, prize: -3 },
      { cellChange: 0, prize: -3 },
      { cellChange: 0, prize: -2 },
      { cellChange: 0, prize: -2 },
      { cellChange: 0, prize: -2 },
      { cellChange: 0, prize: -2 },
      { cellChange: 0, prize: -1 },
      { cellChange: 0, prize: -1 },
      { cellChange: 0, prize: -1 },
      { cellChange: 0, prize: -1 },
      { cellChange: 0, prize: 0, isJackPot: true, winner: null },
      { cellChange: 0, prize: 0, isJackPot: true, winner: null },
      { cellChange: 0, prize: 0, isJackPot: true, winner: null },
      { cellChange: 0, prize: 0, isJackPot: true, winner: null },
      { cellChange: 0, prize: 0, isJackPot: true, winner: null },
      { cellChange: 0, prize: 0, isJackPot: true, winner: null },
      { cellChange: 0, prize: 0, isJackPot: true, winner: null },
    ],
    initialCashValue: 15,
    minNumberOfSteps: 1,
    maxNumberOfSteps: 5,
    maxPrize: 30,
    currency: "фишек",
    jackPotPrize: 30,
    achivementPrizes: {
      unlucky: 5,
      careful: 5,
      collector: 5,
      lucky: 5,
    },
  },
  loto: {
    min: 1,
    max: 50,
    cardNumbersAmount: 10,
  },
};
