import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import RestoreRoundedIcon from "@mui/icons-material/RestoreRounded";
import { Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Stack, Tooltip, Typography } from "@mui/material";
import AppChip from "../../../components/ui/AppChip";
import AppInfoAlert from "../../../components/ui/AppInfoAlert";
import AppPillButton from "../../../components/ui/AppPillButton";
import type { LottoBingoSavedGame } from "../types";

export default function LottoBingoSavedGamesDialog({ open, games, currentId, disabled, onClose, onRestore, onDelete }: { open: boolean; games: LottoBingoSavedGame[]; currentId: string | null; disabled: boolean; onClose: () => void; onRestore: (id: string) => void; onDelete: (id: string) => void; }) {
  return <Dialog open={open} onClose={disabled ? undefined : onClose} fullWidth maxWidth="md"><DialogTitle>Сохранённые игры Лото Бинго</DialogTitle><DialogContent dividers>{!games.length ? <AppInfoAlert>В этом проекте пока нет сохранённых игр.</AppInfoAlert> : <Stack spacing={1.25}>{games.map((game) => <Stack key={game.id} direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ sm: "center" }} spacing={1} sx={{ p: 1.5, border: "1px solid", borderColor: "divider", borderRadius: 1.75 }}><Stack spacing={0.5}><Stack direction="row" spacing={0.75} alignItems="center" flexWrap="wrap"><Typography fontWeight={700}>{game.meta.configName}</Typography><AppChip size="small" label={game.meta.phase} color={game.meta.status === "finished" ? "success" : "info"} />{game.id === currentId ? <AppChip size="small" label="Текущая" color="secondary" /> : null}</Stack><Typography variant="body2" color="text.secondary">Игроков: {game.state.playersCount} · бочонков: {game.state.drawnBarrelsCount} · ведущий: {game.meta.host.nickname}</Typography></Stack><Stack direction="row"><Tooltip title="Восстановить"><span><IconButton color="primary" disabled={disabled} onClick={() => onRestore(game.id)}><RestoreRoundedIcon /></IconButton></span></Tooltip><Tooltip title="Удалить"><span><IconButton color="error" disabled={disabled} onClick={() => onDelete(game.id)}><DeleteOutlineRoundedIcon /></IconButton></span></Tooltip></Stack></Stack>)}</Stack>}</DialogContent><DialogActions><AppPillButton color="inherit" disabled={disabled} onClick={onClose}>Закрыть</AppPillButton></DialogActions></Dialog>;
}
